/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GenerationModesRouteImport } from './routes/generation-modes'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai/generate'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationModesRoute = GenerationModesRouteImport.update({
  id: '/generation-modes',
  path: '/generation-modes',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/generation-modes': typeof GenerationModesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/generation-modes': typeof GenerationModesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/generation-modes': typeof GenerationModesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/generation-modes'
    | '/how-it-works'
    | '/reset-password'
    | '/api/ai/generate'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/generation-modes'
    | '/how-it-works'
    | '/reset-password'
    | '/api/ai/generate'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/generation-modes'
    | '/how-it-works'
    | '/reset-password'
    | '/api/ai/generate'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  GenerationModesRoute: typeof GenerationModesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation-modes': {
      id: '/generation-modes'
      path: '/generation-modes'
      fullPath: '/generation-modes'
      preLoaderRoute: typeof GenerationModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  GenerationModesRoute: GenerationModesRoute,
  HowItWorksRoute: HowItWorksRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
